from .chess960 import (
    FAMILY_KEY as CHESS960_FAMILY,
    GENERATOR_VERSION as CHESS960_GENERATOR_VERSION,
)
from .dice_chess import (
    GENERATOR_VERSION as DICE_CHESS_PROBABILITY_GENERATOR_VERSION,
)
from .dice_chess_world import (
    FAMILY_KEY as DICE_CHESS_FAMILY,
    GENERATOR_VERSION as DICE_CHESS_GENERATOR_VERSION,
)
from .dice_chess_position import (
    GENERATOR_VERSION as DICE_CHESS_POSITION_GENERATOR_VERSION,
)
from .penultima import (
    FAMILY_KEY as PENULTIMA_FAMILY,
    GENERATOR_VERSION as PENULTIMA_GENERATOR_VERSION,
)

__all__ = [
    "CHESS960_FAMILY",
    "CHESS960_GENERATOR_VERSION",
    "DICE_CHESS_FAMILY",
    "DICE_CHESS_GENERATOR_VERSION",
    "DICE_CHESS_POSITION_GENERATOR_VERSION",
    "DICE_CHESS_PROBABILITY_GENERATOR_VERSION",
    "PENULTIMA_FAMILY",
    "PENULTIMA_GENERATOR_VERSION",
]
