export {
  ParticipantWorkspace,
  type ChessBoard,
  type ChessBoardCell,
  type ChessDie,
  type ChessDiceSet,
  type ChessPieceCode,
  type ChessPieceKind,
  type DiceFaces,
  type DicePieceKind,
  type ParticipantTask,
  type ParticipantWorkspaceProps,
  type PenultimaObservation,
  type TaskMoveTransitionResult,
  type TaskTransitionResult,
} from "./ParticipantWorkspace";
